/* user*/
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (1, 'Alex', 'single', '365897');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (2, 'Rosh', 'single', '258746');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (3, 'David', 'single', '123456');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (4, 'Sam', 'single', '2589645');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (5, 'Test', 'married', '123456');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (6, 'Happy', 'single', '123658958');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (7, 'Sara', 'single', '25698');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (8, 'Yad', 'married', '214587');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (9, 'Mutlu', 'single', '123456');
INSERT INTO "CUSTOMER" ("ID","FULLNAME","MARRIEDSTATUS","PHONENUMBER") VALUES (10, 'Mesut', 'married', '123456');
